### ISSUE TITLE
Phone number in REGISTER and EDIT PERSONNAL DATA functions

### ISSUE THREAD

**Issue by Tabardelli** [campus-digital-valence/projet_de_revv#106]
Due to model change the phone numbers are not saved in the database during those process.

**Comment by Noksit** [comment]
aie donte eundeurstaind ...

mais si tu dit que cest a cause des protected fillable, (il y a phone_number_1 et phone_number_2), nico l'a fix dans une de ses pull request.

**Comment by cbouvat** [comment]
C'est résolu, c'est clean !
