### ISSUE TITLE
Form Register User

### ISSUE THREAD

**Issue by mariefontanel** [campus-digital-valence/projet_de_revv#28]
Add field {{value=old('')}} with if else condition for the radio buttons and selects

**Comment by mariefontanel** [comment]
the code looks like this : 
<select id="gender" name="gender" class="form-control">
         <option>{{ __('Civility') }}</option>
         <option value="1" @if(old('gender') ==1)selected @endif> {{ __('Male') }}</option>
         <option value="2" @if(old('gender') ==2)selected @endif>{{ __('Female') }}</option>
</select>

**Comment by Ghis26** [comment]
Issue resolved
